# Generated by Django 5.0.6 on 2024-06-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesettings',
            name='description',
        ),
    ]
