# Generated by Django 5.0.6 on 2024-06-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_imagesettings_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSettings',
        ),
    ]
