# Generated by Django 5.0.6 on 2024-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imagesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', max_length=254, upload_to='', verbose_name='images/'),
        ),
    ]
