# Generated by Django 5.0.6 on 2024-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, default='', max_length=254, verbose_name='url')),
                ('icon', models.CharField(blank=True, default='', max_length=254, verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
