# Generated by Django 5.0.6 on 2024-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Name')),
                ('file', models.ImageField(blank=True, default='', max_length=254, upload_to='', verbose_name='documents/')),
                ('button_text', models.CharField(blank=True, default='', max_length=254, verbose_name='Button Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
