# Generated by Django 5.0.6 on 2024-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_document_name_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', max_length=254, upload_to='', verbose_name='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=254, verbose_name='Slug'),
        ),
    ]
